### ISSUE TITLE
List of glitches we have discovered after 2.2.1 update so far

### ISSUE THREAD

**Issue by taskmaster19** [tukasa0001/TownOfHost#887] opened 2022-07-15 13:23 UTC
I host a modded lobby for a group of people, and it's been several days of us having great fun with the latest version of your work. Here are some occasions that we, during these days, noticed to be present:

_Noticed in previous issue reports here and seen by us too_:
- Sheriff self-killing themselves multiple times as ghost (also happened to Arsonist)
- Shapeshifting causing a kick or ban from the lobby
- Dictator's vote not working with Witch-curse mechanics (the cursed dies even if the Dicator's vote is correct)

_Occured more than 1 time / for different players_:
- Black screen at the moment game starts - most common problem right now (2-3 players every other match) - happens to all roles - seldom fixes itself after one meeting
- Snitch doesn't get info about Imposters (no arrows, no red names) after completing all tasks if they are a Lover (even if their Lover is also on team Crew) - screenshots below - we found it a bit strange but please let me know if that is the way that you intended such combination to work
- Players as ghosts after death can't fly through walls (and open doors) - occured to roles of Mayor and Dictator so far - fixes itself after one meeting
- Sort of desync with the killed player appearing as still alive on screens of some of the players after the report - sometimes - never happens for Host

![image](https://user-images.githubusercontent.com/108941982/179231391-60b6fe1e-bf83-4934-9617-d5c43227540a.png)
![image](https://user-images.githubusercontent.com/108941982/179231421-b0d3074e-b414-44f7-8bde-54efcc1a9085.png)
![image](https://user-images.githubusercontent.com/108941982/179231447-473ae77e-b9be-42de-a8c4-cdeb06547198.png)

_Occured only once so far_:
- Player could see red names of Imposters right after the start, as yet alive
- Same thing with Sheriff's role seen above their name
- Player could see everyone's roles - then died without being killed (confirmedly not a death from Vampire or same kind) after a meeting/report was called
- Imposters' names are shown in red in the meeting for players of roles other than Snitch - happened to Arsonist

That's about it. Regardless of everything above, your work keeps giving us wonderful time and we immensely appreciate all the effort that you put into it. Hope you have enough time for everything and it all goes well for you.

**Comment by Tommy-XL** [comment] 2022-07-15 18:15
I will say that if Snitch becomes a lover, he cannot do tasks, this is not a bug and it should be so

**Comment by taskmaster19** [comment] 2022-07-16 15:49
> * Player could see everyone's roles - then died without being killed (confirmedly not a death from Vampire or same kind) after a meeting/report was called

UPD: seemed to happen again - a player (Opportunist) could see everyone else's roles during a meeting

**Comment by The3headedNinja** [comment] 2022-07-20 17:56
> I will say that if Snitch becomes a lover, he cannot do tasks, this is not a bug and it should be so

what do you man? that snitch shouldnt be able to do tasks i believe this is a host only issue and should be fixed

**Comment by tampopo-dandelion** [comment] 2022-07-27 01:11
> - Sheriff self-killing themselves multiple times as ghost (also happened to Arsonist)
> 
this is measures for darkening .it is not bug
in the next time, please ask us in our discord server.

**Comment by GrossOutD** [comment] 2022-07-28 13:21
black screen happens without the mod, its an innersloth issue not town of host issue

**Comment by tampopo-dandelion** [comment] 2022-07-29 08:37
No, if there is a shellif, there will be a blackout. However, it seems that you may have found something that can avoid the blackout without killing recently, so please wait.

**Comment by yurinakira** [comment] 2022-08-08 02:23
報告のルールがあるのでそれに沿って報告してください。

**Closed** 2022-08-08 02:23 UTC
